# Generated by Django 3.2.5 on 2021-07-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tagline',
            field=models.CharField(default='Enter your Tagline', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
