# Generated by Django 3.2.5 on 2021-07-17 09:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210716_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='default_featured_image.jpg', upload_to='featured_images/'),
        ),
    ]
