# Generated by Django 3.2.5 on 2021-07-16 08:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='changelogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_title', models.CharField(max_length=100)),
                ('version_description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'changelogsModel',
                'verbose_name_plural': 'changelogsModels',
            },
        ),
    ]
