# Generated by Django 3.2.5 on 2021-07-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogsmodel',
            name='version_description',
            field=models.TextField(),
        ),
    ]
