# Generated by Django 3.2.5 on 2021-07-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0002_alter_changelogsmodel_version_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogsmodel',
            options={'verbose_name': 'Changelog', 'verbose_name_plural': 'Changelogs'},
        ),
    ]
