# Generated by Django 3.2.5 on 2021-07-17 09:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0003_alter_changelogsmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelogsmodel',
            name='version_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
