# Generated by Django 3.2.5 on 2021-08-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpages', '0005_changelogsmodel_version_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact Form',
                'verbose_name_plural': 'Contact Forms',
            },
        ),
    ]
